[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#4f8af9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333f"
font = "sans serif"